name: corpus
description: "Personal & social video game tracker."
publish_to: 'none'
version: 1.1.3+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.16.0
  http: ^1.6.0
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  file_picker: ^11.0.3
  csv: ^6.0.0
  flutter_image_compress: ^2.5.1
  liquid_glass_easy: ^3.5.0

  # Push notifications
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  google_fonts: ^8.2.1
  audioplayers: ^6.8.1
  web: ^1.1.1
  archive: ^4.0.7
  path_provider: ^2.1.5
  path: ^1.9.1
  image_cropper: ^12.2.1

  cross_file: ^0.3.5+4
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/guest_showcase/
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne/static/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne/static/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne/static/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne/static/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne/static/Syne-ExtraBold.ttf
          weight: 800

# flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000000"
    theme_color: "#7E57C2"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

