// lib/utils/achievement_utils.dart

class AchievementUtils {
  static const Map<String, Map<String, int?>> achievementIgdbIds = {
    'kojima': {'companyId': 170},
    'fromsoftware': {'companyId': 1012},
    'nintendo': {'companyId': 70},
    'capcom': {'companyId': 37},
    'naughty_dog': {'companyId': 401},
    'rockstar': {'companyId': 29},
    'cd_projekt': {'companyId': 908},
    'valve': {'companyId': 56},
    'square_enix': {'companyId': 26},
    'bethesda': {'companyId': 16565},
    'konami': {'companyId': 129},
    'remedy': {'companyId': 305},
    'team_ninja': {'companyId': 769},
    'pokemon': {'companyId': 1617},
    'zelda': {'collectionId': 106},
    'mario': {'collectionId': 240},
    'halo': {'franchiseId': 137},
    'sonic': {'collectionId': 2156},
    'persona': {'franchiseId': 552, 'franchiseId2': 538},
    'dark_souls': {'collectionId': 543, 'franchiseId': 1124},
    'assassins_creed': {'franchiseId': 571},
    'yakuza': {'franchiseId': 1467},
    'resident_evil': {'franchiseId': 29},
    'final_fantasy': {'franchiseId': 4},
    'call_of_duty': {'franchiseId': 726},
    'elder_scrolls': {'franchiseId': 456},
    'god_of_war': {'franchiseId': 2098},
    'tomb_raider': {'franchiseId': 279},
    'monster_hunter': {'franchiseId': 824},
    'kingdom_hearts': {'franchiseId': 720},
    'silent_hill': {'franchiseId': 554},
    'metroid': {'franchiseId': 756},
    'kirby': {'franchiseId': 789},
    'devil_may_cry': {'franchiseId': 834},
    'castlevania': {'franchiseId': 895},
    'mass_effect': {'franchiseId': 1048},
    'doom': {'franchiseId': 798},
    'bioshock': {'collectionId': 1},
    'borderlands': {'franchiseId': 808},
    'metro': {'franchiseId': 1344},
    'dead_space': {'franchiseId': 1386},
    'xenoblade': {'franchiseId': 4564},
  };
}
