name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Esta acción instala Flutter en el servidor de GitHub
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar código
        run: flutter analyze

      # Si tienes pruebas unitarias en tu carpeta /test, esto las ejecutará
      - name: Ejecutar pruebas
        run: flutter test
